[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "feedfinder2"
dynamic = ["version", "authors", "license", "classifiers"]
description = "Find the feed URLs for a website."
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4 = \"^4.12.2\"",
    "lxml>=5.4.0",
    "requests>=2.32.3",
    "six>=1.17.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
